"""Static enum-guard scope data. GENERATED by scripts/build_permission_resources.py -- do not edit by hand.

ENUM_REQUIRED_SCOPES[command] lists each required endpoint and the delegated Graph
scopes that satisfy it (any one suffices). The guard warns/prompts when the active
client holds none of them (and not the WILDCARD_SCOPE) for some required endpoint.
"""

ENUM_REQUIRED_SCOPES = {
    "organization": [
        {
            "endpoint": "GET /organization",
            "accepted": [
                "user.read",
                "organization.read.all",
                "directory.read.all",
                "organization.readwrite.all",
                "directory.readwrite.all"
            ]
        }
    ],
    "current-user": [
        {
            "endpoint": "GET /me",
            "accepted": [
                "user.read",
                "user.readwrite",
                "user.readbasic.all",
                "user.read.all",
                "user.readwrite.all",
                "directory.read.all",
                "directory.readwrite.all"
            ]
        }
    ],
    "current-user-memberships": [
        {
            "endpoint": "GET /me/transitiveMemberOf",
            "accepted": [
                "user.read",
                "directory.read.all",
                "directory.readwrite.all",
                "group.read.all",
                "groupmember.read.all",
                "user.read.all"
            ]
        }
    ],
    "users": [
        {
            "endpoint": "GET /users",
            "accepted": [
                "user.readbasic.all",
                "user.read.all",
                "user.readwrite.all",
                "directory.read.all",
                "directory.readwrite.all"
            ]
        }
    ],
    "groups": [
        {
            "endpoint": "GET /groups",
            "accepted": [
                "group-nestingsupport.readwrite.all",
                "directory.read.all",
                "directory.readwrite.all",
                "group.manageprotection.all",
                "group.read.all",
                "group.readwrite.all",
                "groupmember.read.all"
            ]
        }
    ],
    "conditional-access": [
        {
            "endpoint": "GET /identity/conditionalAccess/policies",
            "accepted": [
                "policy.read.all"
            ]
        }
    ],
    "service-principals": [
        {
            "endpoint": "GET /servicePrincipals",
            "accepted": [
                "application.read.all",
                "application.readwrite.all",
                "directory.read.all",
                "directory.readwrite.all"
            ]
        },
        {
            "endpoint": "GET /organization",
            "accepted": [
                "user.read",
                "organization.read.all",
                "directory.read.all",
                "organization.readwrite.all",
                "directory.readwrite.all"
            ]
        },
        {
            "endpoint": "GET /servicePrincipals/{id}/appRoleAssignments",
            "accepted": [
                "application.read.all",
                "application.readwrite.all",
                "directory.read.all",
                "directory.readwrite.all"
            ]
        }
    ],
    "privileged-role-assignments": [
        {
            "endpoint": "GET /roleManagement/directory/roleDefinitions",
            "accepted": [
                "rolemanagement.read.directory",
                "directory.read.all",
                "rolemanagement.readwrite.directory",
                "directory.readwrite.all"
            ]
        },
        {
            "endpoint": "GET /roleManagement/directory/roleAssignments",
            "accepted": [
                "rolemanagement.read.directory",
                "rolemanagement.read.all",
                "directory.read.all",
                "rolemanagement.readwrite.directory",
                "directory.readwrite.all"
            ]
        }
    ],
    "all": [
        {
            "endpoint": "GET /organization",
            "accepted": [
                "user.read",
                "organization.read.all",
                "directory.read.all",
                "organization.readwrite.all",
                "directory.readwrite.all"
            ]
        },
        {
            "endpoint": "GET /me",
            "accepted": [
                "user.read",
                "user.readwrite",
                "user.readbasic.all",
                "user.read.all",
                "user.readwrite.all",
                "directory.read.all",
                "directory.readwrite.all"
            ]
        },
        {
            "endpoint": "GET /me/transitiveMemberOf",
            "accepted": [
                "user.read",
                "directory.read.all",
                "directory.readwrite.all",
                "group.read.all",
                "groupmember.read.all",
                "user.read.all"
            ]
        },
        {
            "endpoint": "GET /users",
            "accepted": [
                "user.readbasic.all",
                "user.read.all",
                "user.readwrite.all",
                "directory.read.all",
                "directory.readwrite.all"
            ]
        },
        {
            "endpoint": "GET /groups",
            "accepted": [
                "group-nestingsupport.readwrite.all",
                "directory.read.all",
                "directory.readwrite.all",
                "group.manageprotection.all",
                "group.read.all",
                "group.readwrite.all",
                "groupmember.read.all"
            ]
        },
        {
            "endpoint": "GET /identity/conditionalAccess/policies",
            "accepted": [
                "policy.read.all"
            ]
        },
        {
            "endpoint": "GET /servicePrincipals",
            "accepted": [
                "application.read.all",
                "application.readwrite.all",
                "directory.read.all",
                "directory.readwrite.all"
            ]
        },
        {
            "endpoint": "GET /servicePrincipals/{id}/appRoleAssignments",
            "accepted": [
                "application.read.all",
                "application.readwrite.all",
                "directory.read.all",
                "directory.readwrite.all"
            ]
        },
        {
            "endpoint": "GET /roleManagement/directory/roleDefinitions",
            "accepted": [
                "rolemanagement.read.directory",
                "directory.read.all",
                "rolemanagement.readwrite.directory",
                "directory.readwrite.all"
            ]
        },
        {
            "endpoint": "GET /roleManagement/directory/roleAssignments",
            "accepted": [
                "rolemanagement.read.directory",
                "rolemanagement.read.all",
                "directory.read.all",
                "rolemanagement.readwrite.directory",
                "directory.readwrite.all"
            ]
        }
    ]
}

CONDITIONAL_ACCESS_SCOPES = [
    "directory.accessasuser.all",
    "policy.read.all"
]

WILDCARD_SCOPE = "directory.accessasuser.all"
